"""Пять версий: всё, что отличает V1..V5. Читается plan.py, audio.py, compose.py и runtime.js."""

STYLES = {
    "V1": dict(
        id="V1", name="Bold Yellow",
        angle="ПРОТИВОРЕЧИВОЕ утверждение (contrarian claim): идёт против привычного мнения, коротко, как удар.",
        bg="designed", matte=True, plate_query=None, ambience=None, music_idx=0,
        font="Montserrat", font_weight=900, caps=True, cap_size=112, cap_words=3,
        colors=dict(text="#FFFFFF", emph="#FFD400", stroke="#000000", accent="#FFD400"),
        hook_style="slam", cam_gap=4.4, snap_on_emph=False, graphics_density=0.3,
        framings=["medium", "close", "medium", "wide"], sfx_level=0.45, push=0.04,
        grade="eq=contrast=1.05:saturation=1.06:brightness=0.005,unsharp=5:5:0.3",
        music_gain_db=-24, music_rel_db=-19, premium=True,
    ),
    "V2": dict(
        id="V2", name="Neon ADHD",
        angle="ВОПРОС (question): провокационный вопрос зрителю, зацепить любопытством.",
        bg="plate", matte=True, plate_query="city center crowd street portrait", ambience="crowd", music_idx=1,
        font="Unbounded", font_weight=900, caps=True, cap_size=88, cap_words=2,
        colors=dict(text="#FFFFFF", emph="#00F5FF", stroke="#1A0033", accent="#FF2BD6"),
        hook_style="glitch", cam_gap=1.75, snap_on_emph=True, graphics_density=1.2,
        framings=["medium", "close", "wide", "close", "medium"], sfx_level=1.0, push=0.05,
        grade="eq=contrast=1.15:saturation=1.35,colorbalance=bs=0.06:bh=0.05:rs=0.03",
        music_gain_db=-23,
    ),
    "V3": dict(
        id="V3", name="Editorial",
        angle="РЕЗУЛЬТАТ СРАЗУ (result first): итог/выгода в первой фразе, спокойно, одной зрелой фразой.",
        bg="plate", matte=True, plate_query="pine forest sunlight trees portrait", ambience="birds", music_idx=2,
        plate_grade="eq=brightness=-0.12:contrast=0.95:saturation=0.8",
        font="Playfair Display", font_weight=700, caps=False, cap_size=84, cap_words=4,
        colors=dict(text="#F6EEDF", emph="#E8B86A", stroke="#1B140C", accent="#E8B86A"),
        hook_style="editorial", cam_gap=4.2, snap_on_emph=False, graphics_density=0.45,
        framings=["medium", "wide", "medium", "close"], sfx_level=0.5, push=0.04,
        grade="eq=contrast=1.04:saturation=0.92:gamma=1.03,colorbalance=rs=0.05:gs=0.01:bs=-0.05:rh=0.04:bh=-0.04",
        music_gain_db=-22,
    ),
    "V4": dict(
        id="V4", name="Chrome 3D",
        angle="ЦИФРА + ВРЕМЯ (number+time): конкретное число и срок («за 3 дня», «в 2 раза»), как заголовок.",
        bg="studio", matte=True, plate_query=None, ambience=None, music_idx=3, globe_behind=True,
        font="Russo One", font_weight=400, caps=True, cap_size=100, cap_words=3,
        colors=dict(text="#E9EEF5", emph="#4DA3FF", stroke="#05070D", accent="#4DA3FF"),
        hook_style="chrome3d", cam_gap=2.8, snap_on_emph=True, graphics_density=0.8,
        framings=["medium", "wide", "close", "medium"], sfx_level=0.9, push=0.06,
        grade="eq=contrast=1.14:saturation=0.95,colorbalance=bs=0.05:bm=0.03",
        music_gain_db=-24,
    ),
    "V5": dict(
        id="V5", name="Soft Pastel",
        angle="БОЛЬ (pain): узнаваемая проблема зрителя, сказанная мягко и с эмпатией.",
        bg="plate", matte=True, plate_query="cozy house birds garden spring portrait", ambience="birds", music_idx=4,
        font="Nunito", font_weight=900, caps=False, cap_size=86, cap_words=4,
        colors=dict(text="#4B3A5A", emph="#FF6F91", stroke="#FFFFFF", accent="#FF9EB5"),
        hook_style="pastel", cam_gap=4.0, snap_on_emph=False, graphics_density=0.4,
        framings=["medium", "wide", "medium"], sfx_level=0.4, push=0.03,
        grade="eq=contrast=0.97:saturation=0.9:brightness=0.03,colorbalance=rh=0.03:bh=0.03",
        music_gain_db=-22,
    ),
}
